FROM pytorch/pytorch:2.4.0-cuda12.4-cudnn9-devel

WORKDIR /app

RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y git

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN CMAKE_ARGS="-DLLAMA_CUBLAS=on" pip install "llama-cpp-python<=0.2.79.0"
COPY *.py ./
ADD llmlib ./llmlib
RUN pip install -e llmlib
ADD .streamlit .streamlit

#CMD [ "python", "--version"]
# CMD ["nvidia-smi"]
# CMD ["nvcc", "--version"]
CMD [ "python", "-m", "streamlit", "run", "st_app.py", "--server.port", "8020"]