FROM pytorch/pytorch:2.4.0-cuda12.4-cudnn9-devel

WORKDIR /app

RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y git

RUN pip install uv
COPY requirements.txt requirements.txt
RUN uv pip install -r requirements.txt --system
RUN pip install flash-attn --no-build-isolation
COPY *.py ./
ADD llmlib ./llmlib
RUN uv pip install -e llmlib --system
ADD .streamlit .streamlit

#CMD [ "python", "--version"]
# CMD ["nvidia-smi"]
# CMD ["nvcc", "--version"]
CMD [ "python", "-m", "streamlit", "run", "st_app.py", "--server.port", "8020"]